# -----------------------------------------------------------
# Configuración del WorkFlow

name: Deploy MkDocs Tarea 2

on:
  push:
    branches:
      - main 

# Permisos

permissions:
  contents: write 
  pages: write
  id-token: write

# Definición del trabajo

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    
    # Paso 1: Obtencion del código fuente
    - name: Clonar Repositorio
      uses: actions/checkout@v4

    # Paso 2: Configuración de Python
    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    # Paso 3: Instalación de dependencias
    - name: Instalar MkDocs y Tema Material y Puglins
      run: pip install mkdocs mkdocs-material mkdocs-glightbox Pygments pymdown-extensions

    # Paso 4: Construir y desplegar la documentación
    - name: Deploy docs
      run: mkdocs gh-deploy --force
      env:

        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

# -----------------------------------------------------------